version: 2.1

orbs:
  maven: circleci/maven@1.1

#workflows:
  #maven_test:
commands:
      buildyls:
            steps:
                - checkout
                #https://circleci.com/docs/2.0/concepts/ :
                - run: ls
      buildyecho:
            steps:
                - checkout
                #https://circleci.com/docs/2.0/concepts/ :
                - run: echo "echoed"          
executors:
      docker-executor:
          docker:
              #- image: circleci/openjdk:9.0.9-12
              - image: circleci/openjdk:11.0
      machine-executor:
        machine:
          image: ubuntu-1604:202007-01
     
jobs:
  #- cd spring-autowired-npe/ && maven/test
  #- maven/test :
      #https://stackoverflow.com/questions/65602920/circleci-maven-build-fails-missing-pom-xml
      #app_src_directory: autoMerge
  #- build: 
   
 
    build-with-dockerJ:
        executor: docker-executor
        steps:
            - buildyls
      #or TODO build jobs
workflows:
  build-with-dockerW:
    jobs:
      - build-with-dockerJ
